# Generated by Django 3.2 on 2021-07-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Food', 'Food'), ('Home', 'Home'), ('Other', 'Other'), ('Pets', 'Pets'), ('Tickets', 'Tickets'), ('Toys', 'Toys')], max_length=15),
        ),
    ]
