# Generated by Django 3.2 on 2021-08-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='c_listing', to='auctions.Comment'),
        ),
    ]
