# Generated by Django 3.2 on 2021-08-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210831_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=20)),
                ('body', models.CharField(max_length=150)),
                ('likes', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
        migrations.AlterField(
            model_name='user',
            name='tweets',
            field=models.ManyToManyField(blank=True, related_name='post_user', to='network.Post'),
        ),
    ]
